<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27084" started-at="2018-12-05T09:08:22Z" finished-at="2018-12-05T09:08:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27084" started-at="2018-12-05T09:08:22Z" finished-at="2018-12-05T09:08:49Z">
      <class name="com.dms.qa.testcases.GroupsManagementPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.dms.qa.testcases.GroupsManagementPageTest@3e6fa38a]" name="setUp" is-config="true" duration-ms="5418" started-at="2018-12-05T14:38:22Z" finished-at="2018-12-05T14:38:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validateCreateNewGroupsManagement(java.lang.String, java.lang.String)[pri:2, instance:com.dms.qa.testcases.GroupsManagementPageTest@3e6fa38a]" name="validateCreateNewGroupsManagement" duration-ms="963" started-at="2018-12-05T14:38:27Z" data-provider="getDMSTestData" finished-at="2018-12-05T14:38:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[na]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Group is not able to added- group already exists expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Group is not able to added- group already exists expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.dms.qa.testcases.GroupsManagementPageTest.validateCreateNewGroupsManagement(GroupsManagementPageTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateNewGroupsManagement -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.dms.qa.testcases.GroupsManagementPageTest@3e6fa38a]" name="tearDown" is-config="true" duration-ms="3000" started-at="2018-12-05T14:38:28Z" finished-at="2018-12-05T14:38:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.dms.qa.testcases.GroupsManagementPageTest@3e6fa38a]" name="setUp" is-config="true" duration-ms="4350" started-at="2018-12-05T14:38:31Z" finished-at="2018-12-05T14:38:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validateCreateNewGroupsManagement(java.lang.String, java.lang.String)[pri:2, instance:com.dms.qa.testcases.GroupsManagementPageTest@3e6fa38a]" name="validateCreateNewGroupsManagement" duration-ms="989" started-at="2018-12-05T14:38:36Z" data-provider="getDMSTestData" finished-at="2018-12-05T14:38:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dff]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[na]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Group is not able to added- group already exists expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Group is not able to added- group already exists expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.dms.qa.testcases.GroupsManagementPageTest.validateCreateNewGroupsManagement(GroupsManagementPageTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateNewGroupsManagement -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.dms.qa.testcases.GroupsManagementPageTest@3e6fa38a]" name="tearDown" is-config="true" duration-ms="3000" started-at="2018-12-05T14:38:37Z" finished-at="2018-12-05T14:38:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.dms.qa.testcases.GroupsManagementPageTest@3e6fa38a]" name="setUp" is-config="true" duration-ms="4773" started-at="2018-12-05T14:38:40Z" finished-at="2018-12-05T14:38:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validateCreateNewGroupsManagement(java.lang.String, java.lang.String)[pri:2, instance:com.dms.qa.testcases.GroupsManagementPageTest@3e6fa38a]" name="validateCreateNewGroupsManagement" duration-ms="1089" started-at="2018-12-05T14:38:45Z" data-provider="getDMSTestData" finished-at="2018-12-05T14:38:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[na]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateNewGroupsManagement -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.dms.qa.testcases.GroupsManagementPageTest@3e6fa38a]" name="tearDown" is-config="true" duration-ms="3000" started-at="2018-12-05T14:38:46Z" finished-at="2018-12-05T14:38:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.dms.qa.testcases.GroupsManagementPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
